apiVersion: v1
kind: Secret
metadata:
  name: harubiru
  labels:
    app: harubiru
type: Opaque
data:
  APP_KEY: YmFzZTY0OmNxbk16dnYzTUlUVFo3SFdMT0oreWltSUxzZmU4cVU4M3laNzJmL1A5YTg9
  DB_USERNAME: aGFydWJpcnU=
  DB_PASSWORD: cmFoYXNpYWJhbmdldA==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: harubiru
  labels:
    app: harubiru
data:
  APP_NAME: HaruBiru
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: http://harubiru.minikube1.local
  LOG_CHANNEL: stack
  DB_CONNECTION: mysql
  DB_HOST: harubiru-mariadb
  DB_PORT: "3306"
  DB_DATABASE: harubiru
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"

---
apiVersion: v1
kind: Service
metadata:
  name: harubiru
  labels:
    app: harubiru
spec:
  selector:
    app: harubiru
  ports:
  - port: 80
    name: harubiru-nginx
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harubiru
  labels:
    app: harubiru
spec:
  selector:
    matchLabels:
      app: harubiru
  template:
    metadata:
      labels:
        app: harubiru
    spec:
      initContainers:
        - name: database-migrations
          image: trianwar/harubiru-fpm:alpine
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: harubiru
            - secretRef:
                name: harubiru
          command:
            - "php"
          args:
            - "artisan"
            - "migrate:fresh"
            - "--seed"
            - "--force"
      containers:
        - name: fpm
          image: trianwar/harubiru-fpm:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              name: harubiru-fpm
          envFrom:
            - configMapRef:
                name: harubiru
            - secretRef:
                name: harubiru
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/storage/logs
            - name: cache
              mountPath: /var/www/html/storage/framework/cache
            - name: sessions
              mountPath: /var/www/html/storage/framework/sessions
            - name: views
              mountPath: /var/www/html/storage/framework/views
            - name: testing
              mountPath: /var/www/html/storage/framework/testing
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 100m
              memory: 50M
        - name: nginx
          imagePullPolicy: IfNotPresent
          image: trianwar/harubiru-nginx:latest
          ports:
            - containerPort: 80
              name: harubiru-nginx
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 100m
              memory: 50M
      volumes:
        - name: logs
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: testing
          emptyDir: {}
        - name: sessions
          emptyDir: {}
        - name: views
          emptyDir: {}
      securityContext:
        fsGroup: 82
